landmark:
  - color: "red"
    x: 8.5
    y: -5.0
    r: 0.1
    h: 0.5
  - color: "green"
    x: 8.5
    y: 5.0
    r: 0.1
    h: 0.5
  - color: "yellow"
    x: 11.5
    y: 5.0
    r: 0.1
    h: 0.5
  - color: "magenta"
    x: 11.5
    y: -5.0
    r: 0.1
    h: 0.5
  - color: "cyan"
    x: 0.0
    y: 0.0
    r: 0.1
    h: 0.5

